# Site settings
title: Carlo Denaro
email: me@carlodenaro.com
url: https://blackout314.github.io
description: "Passionate and smart nerd, loves coding, new amazing tecnology and experiments."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Carlo Denaro
  location: Hire me
  social: Around the Web
  credits: Friends

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://it.linkedin.com/in/carlodenaro/
  - title: stack-overflow
    url: https://stackoverflow.com/users/4428662/carlo-denaro
  - title: github
    url: http://github.com/blackout314
  - title: bitbucket
    url: http://bitbucket.org/blackout314
  - title: google-plus
    url: https://plus.google.com/+carlodenaro
  - title: twitter
    url: http://twitter.com/carlodenaro
  - title: facebook
    url: https://www.facebook.com/carlodenarocom
  - title: pinterest
    url: https://www.pinterest.com/carlodenaro

# Postal address (add as many lines as necessary)
address:
  - line: You can hire me
  - line: use the contact form

# Credits content
credits: '<a href="http://www.grayhats.org" target="_blank">GrayHats</a><br/><a href="http://italyremote.com/" target="_blank">Italy Remote</a>'

# Build settings
markdown: kramdown
permalink: pretty
